name: SecureChat Server 앱 빌드
on:
  push:
    tags:
      - v*
permissions:
  contents: read
  packages: write
env:
  SECURECHAT_DOMAIN: localhost
  SECURECHAT_RABBITMQ_HOST: ${{ secrets.RABBITMQ_HOST }}
  SECURECHAT_RABBITMQ_PORT: ${{ secrets.RABBITMQ_PORT }}
  SECURECHAT_RABBITMQ_CLIENT_NAME: ${{ secrets.RABBITMQ_CLIENT_NAME }}
  SECURECHAT_RABBITMQ_CLIENT_PASSCODE: ${{ secrets.RABBITMQ_CLIENT_PASSCODE }}
  SECURECHAT_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  SECURECHAT_DYNAMODB_TABLE_NAME: ${{ secrets.DYNAMODB_TABLE_NAME }}
  SECURECHAT_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  SECURECHAT_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  SECURECHAT_AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-java@4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: gradlew 빌드
        run: ./gradlew build
      - name: 이미지 레지스트리 로그인
        uses: docker/login-action@3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 메타데이터 설정
        id: meta
        uses: docker/metadata-action@5
        with:
          images: ghcr.io/${{ github.repository_owner }}/securechat/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
      - name: 이미지 빌드 & 푸쉬
        uses: docker/build-push-action@5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
